# Generated by Django 5.1.5 on 2025-06-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shoppingcart_cartproducts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproducts',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoriteproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favoriteproducts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartProducts',
        ),
        migrations.DeleteModel(
            name='favoriteProducts',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
