# Generated by Django 5.1.5 on 2025-07-30 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_favoriteproducts_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_buyer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('common', 'Usuario común'), ('group', 'Agrupación campesina'), ('admin', 'Administrador')], default='common', max_length=10),
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('organization_type', models.CharField(choices=[('cooperative', 'Cooperativa'), ('association', 'Asociación'), ('informal', 'Grupo informal'), ('other', 'Otro')], default='other', max_length=100)),
                ('legal_representative', models.CharField(max_length=150)),
                ('representative_cedula', models.CharField(max_length=20)),
                ('image_cedula', models.ImageField(blank=True, null=True, upload_to='documents/cedula/')),
                ('rut_document', models.FileField(blank=True, null=True, upload_to='documents/rut/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
