# Generated by Django 5.1.5 on 2025-08-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile_pictures/perfil.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
