# Generated by Django 5.1.5 on 2025-06-23 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='confirmed_buyer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='confirmed_seller',
        ),
        migrations.AddField(
            model_name='detailinvoice',
            name='confirmed_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailinvoice',
            name='confirmed_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailinvoice',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
