# Generated by Django 5.1.5 on 2025-06-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_confirmed_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinvoice',
            name='confirmed_buyer',
        ),
        migrations.RemoveField(
            model_name='detailinvoice',
            name='confirmed_seller',
        ),
    ]
