# Generated by Django 5.1.5 on 2025-08-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_detailinvoice_confirmed_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
    ]
