# Generated by Django 5.1.5 on 2025-08-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
