# Generated by Django 5.1.5 on 2025-08-26 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoice_status'),
        ('offers_and_coupons', '0003_remove_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinvoice',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_invoices', to='offers_and_coupons.offers'),
        ),
    ]
