# Generated by Django 5.1.5 on 2025-08-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_detailinvoice_offer'),
        ('offers_and_coupons', '0004_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinvoice',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_invoices', to='offers_and_coupons.coupon'),
        ),
    ]
