# Generated by Django 5.1.5 on 2025-08-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='commentsimage',
            options={'verbose_name': 'Image Comment', 'verbose_name_plural': 'Images Comments'},
        ),
    ]
