# Generated by Django 5.1.5 on 2025-08-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_and_coupons', '0002_alter_offers_product_alter_offers_seller_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
    ]
