# Generated by Django 5.1.5 on 2025-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_and_coupons', '0003_remove_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
