# Generated by Django 5.1.5 on 2025-08-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_commentsimage_image_grades'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
