# Generated by Django 5.1.5 on 2025-08-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsimage',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='CommentsImage',
        ),
    ]
