# Generated by Django 5.1.5 on 2025-08-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_commentsimage_comment_delete_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Image Product', 'verbose_name_plural': 'Images Products'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
