# Generated by Django 5.1.5 on 2025-08-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_options_alter_grades_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories_picture/default.jpeg', upload_to='categories_picture/'),
        ),
    ]
